CREATE TABLE tickets
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    movie VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    sname VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    email VARCHAR(255) NOT NULl,
    nmb INTEGER NOT NULL,
    PRIMARY KEY (id)
);